# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

from datetime import date
current_year = date.today().year

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os
import sys

import django
sys.path.insert(0, os.path.abspath('..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'src.core.settings'
django.setup()

# -- Project information -----------------------------------------------------

project = 'Introducción a ¿Vue.js o HTMX? con Django'
copyright = '2022, FernandoPrzGmz'
author = 'FernandoPrzGmz'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # region sphinx extensions
    # Permite escribir los docstrings con la convención NumPy o Google.
    'sphinx.ext.napoleon',
    
    # Genera la documentación a partir de los docstrings del código fuente
    'sphinx.ext.autodoc',
    
    # Genera automáticamente archivos .rst para automatizar el trabajo que hace autodoc
    'sphinx.ext.autosummary',
    
    # Permite ver el código fuente desde la documentación
    'sphinx.ext.viewcode',

    # Permite hacer links entre documentaciones
    'sphinx.ext.intersphinx',
    # endregion
]

# Boolean indicating whether to scan all found documents for autosummary
# directives, and to generate stub pages for each. It is enabled by default.
# Can also be a list of documents for which stub pages should be generated.
autosummary_generate = True

# A boolean flag (default is False) indicating whether to document classes and
# functions imported in modules.
# autosummary_imported_members = True

# The default options for autodoc directives. They are applied to all autodoc
# directives automatically. It must be a dictionary which maps option names to
# the values.
autodoc_default_options = {
    'members': None,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    # 'exclude-members': '__weakref__'
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# The document name of the “root” document, that is, the document that contains
# the root toctree directive.
# Default is 'index'.
root_doc = 'contents'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# material theme options (see theme.conf for more information)
html_theme_options = {}